---
title: "The Montmort's Problem"
author: "Yuri Antonelli"
date: "`r Sys.Date()`"
output: html_document
---

## The Montmort's Problem
Consider a well shuffled deck of n cards labeled 1 through n. You flip over the cards one by one, saying the numbers 1 through n as you do so. You win the game if, at some point, the number you say aloud is the same as the number on the number on the card being flipped over (for example, if the 7th card in the deck has the label 7). What is the probability of winning?

### Analytical Solution
Let $A_j$ be the event "$j_{\text{th}}$ card matches".

We start from $P(A_j)$, which is simply $\frac{1}{n}$ as all positions are equally likely.

$P(A_1 \cap A_2) = \frac{(n-2)!}{n!} = \frac{1}{n(n-1)}$, since there are $n!$ permutations of the deck, while the 1st and 2nd positions are fixed and the other $n-2$ cards can have any order.

$P(A_1 \cap \ldots \cap A_k) = \frac{(n-k)!}{n!}$.

Now, we can apply **inclusion-exclusion**:

$P(A_1 \cup A_2 \cup \ldots \cup A_n) = n \left(\frac{1}{n}\right) - \binom{n}{2} \left(\frac{1}{n(n-1)}\right) + \binom{n}{3} \left(\frac{1}{n(n-1)(n-2)}\right) + \ldots$

$= 1 - \frac{1}{2!} + \frac{1}{3!} - \ldots$, which is the Taylor series expansion of $1 - \left(\frac{1}{e}\right)$.

### Simulated Solution
```{r}
montmort <- function(n_cards, n_sim) {
  
  # Label n cards
  cards <- 1:n_cards
  
  # Create empty matrix to store simulations
  store_matrix <- matrix(0, nrow = n_cards, ncol = n_sim)
  
  # Fill the first column with the unshuffled deck
  store_matrix[, 1] <- cards
  
  # Fill the matrix by shuffling the deck
  for (i in 2:n_sim) {
    store_matrix[, i] <- sample(cards)
  }
  
  # Check the winning rate
  counter <- numeric(n_sim - 1)
  
  for (i in 2:n_sim) {
    if (any(store_matrix[, 1] == store_matrix[, i])) { # At least one match
      counter[i - 1] <- 1
    }
  }
  
  # Calculate the winning probability
  prob <- mean(counter)
  prob
}

#--------------------------------

# Test
# lets do a graph with different number of cards (from 2 to 1000)
n = seq(from = 2, to = 1000, by = 1)
p = sapply(n, function(x) montmort(x, 1000))

plot(n, p, type = "p", col = "blue", pch = 16, xlab = "Number of Cards", ylab = "Probability to Win")
title("Probability to Win vs. Number of Cards")
abline(h = 1 - 1/exp(1), col = "red", lwd = 2)
legend("topright", legend = "1 - 1/e", col = "red", lwd = 2)
```